<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <RootNamespace>RedeTim.ChatClient</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Confluent.Kafka" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../RedeTim.Contracts/RedeTim.Contracts.csproj" />
    </ItemGroup>

</Project>
