<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <RootNamespace>RedePanda.ChatClient</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <!-- Version pinned in Directory.Packages.props. -->
        <PackageReference Include="Confluent.Kafka" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../RedePanda.Contracts/RedePanda.Contracts.csproj" />
    </ItemGroup>

</Project>
