#!/usr/bin/env bash
# Builds both application images under an immutable version tag and writes the release file
# that deploys them. Optionally loads the images into a local cluster.
#
#   ./scripts/build-images.sh                  # build only
#   ./scripts/build-images.sh --load kind      # build, then load into kind
#   ./scripts/build-images.sh --load minikube  # build, then load into minikube
#   ./scripts/build-images.sh --release        # refuse to build from an unclean working tree
#
# Docker Desktop with Kubernetes enabled needs no load step: it shares one image store.
#
# The tag is derived, never chosen: <appVersion from Chart.yaml>-g<short sha>, e.g.
# 0.1.0-g103b98b. It is never reused, so one tag names exactly one build -- which is what makes
# `helm rollback` restore an actual image rather than the same mutable name it started from.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CHART_DIR="${REPO_ROOT}/deploy/helm/redetim"
RELEASE_DIR="${REPO_ROOT}/deploy/releases"

LOAD_INTO=""
REQUIRE_CLEAN=0
CLUSTER_NAME="${CLUSTER_NAME:-kind}"
MINIKUBE_PROFILE="${MINIKUBE_PROFILE:-minikube}"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --load) LOAD_INTO="${2:-}"; shift 2 ;;
        --release) REQUIRE_CLEAN=1; shift ;;
        -h|--help) sed -n '2,14p' "$0"; exit 0 ;;
        *) echo "Unknown argument: $1" >&2; exit 2 ;;
    esac
done

APP_VERSION="$(sed -n 's/^appVersion:[[:space:]]*"\{0,1\}\([^"[:space:]]*\)"\{0,1\}[[:space:]]*$/\1/p' \
    "${CHART_DIR}/Chart.yaml")"
if [[ -z "${APP_VERSION}" ]]; then
    echo "Could not read appVersion from ${CHART_DIR}/Chart.yaml" >&2
    exit 2
fi

if ! git -C "${REPO_ROOT}" rev-parse --git-dir >/dev/null 2>&1; then
    echo "Not a git repository, so no commit can identify this build." >&2
    echo "Set IMAGE_TAG=<something> to build anyway; the result is not a release." >&2
    exit 2
fi

GIT_SHA="$(git -C "${REPO_ROOT}" rev-parse HEAD)"
VERSION="${APP_VERSION}-g$(git -C "${REPO_ROOT}" rev-parse --short=7 HEAD)"
DIRTY=false

if [[ -n "$(git -C "${REPO_ROOT}" status --porcelain)" ]]; then
    DIRTY=true
    DIRTY_HASH="$({
        git -C "${REPO_ROOT}" diff HEAD
        git -C "${REPO_ROOT}" ls-files -o --exclude-standard -z \
            | (cd "${REPO_ROOT}" && xargs -0 -r sha256sum)
    } | sha256sum | cut -c1-7)"
    VERSION="${VERSION}-dirty.${DIRTY_HASH}"
fi

if [[ -n "${IMAGE_TAG:-}" ]]; then
    echo "!! IMAGE_TAG is set: building '${IMAGE_TAG}' instead of '${VERSION}'."
    echo "!! No release file is written and the result identifies no commit."
    VERSION="${IMAGE_TAG}"
fi

if [[ "${DIRTY}" == true ]]; then
    if [[ "${REQUIRE_CLEAN}" -eq 1 ]]; then
        echo "Refusing to cut a release from an unclean working tree." >&2
        echo "Commit or stash first, then re-run. Without --release this builds anyway." >&2
        git -C "${REPO_ROOT}" status --short >&2
        exit 1
    fi
    echo "!! Working tree is dirty -- this build is NOT a reproducible release."
    echo "!! The tag names the uncommitted content, but nothing in git does."
fi

BACKEND="redetim-backend:${VERSION}"
FRONTEND="redetim-frontend:${VERSION}"

CHATCLIENT="redetim-chatclient:${VERSION}"

if command -v podman >/dev/null 2>&1; then
    ENGINE=podman
elif command -v docker >/dev/null 2>&1; then
    ENGINE=docker
else
    echo "Neither podman nor docker found on PATH." >&2
    exit 1
fi

echo "==> Building ${VERSION} with ${ENGINE}"
"${ENGINE}" build -f "${REPO_ROOT}/src/RedeTim.Backend/Dockerfile" -t "${BACKEND}" "${REPO_ROOT}"
"${ENGINE}" build -f "${REPO_ROOT}/src/RedeTim.ChatClient/Dockerfile" -t "${CHATCLIENT}" "${REPO_ROOT}"
"${ENGINE}" build -t "${FRONTEND}" "${REPO_ROOT}/src/RedeTim.Frontend"

echo "==> Built ${BACKEND}, ${CHATCLIENT} and ${FRONTEND}"

RELEASE_FILE=""
if [[ -z "${IMAGE_TAG:-}" ]]; then
    mkdir -p "${RELEASE_DIR}"
    RELEASE_FILE="${RELEASE_DIR}/${VERSION}.yaml"
    cat > "${RELEASE_FILE}" <<EOF
# Generated by scripts/build-images.sh -- do not edit.
#
# This file is the release: it names the exact images a build produced. Passing it to helm is
# what binds that build to the chart's configuration, and it is what a later \`helm rollback\`
# restores. Commit it, unless the version says dirty.
release:
  version: "${VERSION}"
  gitSha: "${GIT_SHA}"
  builtAt: "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  dirty: ${DIRTY}

backend:
  image:
    tag: "${VERSION}"
frontend:
  image:
    tag: "${VERSION}"
chatClient:
  image:
    tag: "${VERSION}"
EOF
    echo "==> Wrote ${RELEASE_FILE#"${REPO_ROOT}/"}"
fi

if [[ -n "${LOAD_INTO}" ]]; then
    case "${LOAD_INTO}" in
        kind)
            if [[ "${ENGINE}" == "podman" ]]; then
                echo "==> Loading into kind cluster '${CLUSTER_NAME}' via image archive"
                TMP="$(mktemp -d)"
                trap 'rm -rf "${TMP}"' EXIT
                for image in "${BACKEND}" "${CHATCLIENT}" "${FRONTEND}"; do
                    podman tag "${image}" "docker.io/library/${image}"
                done
                podman save -o "${TMP}/backend.tar" "docker.io/library/${BACKEND}"
                podman save -o "${TMP}/chatclient.tar" "docker.io/library/${CHATCLIENT}"
                podman save -o "${TMP}/frontend.tar" "docker.io/library/${FRONTEND}"
                kind load image-archive "${TMP}/backend.tar" --name "${CLUSTER_NAME}"
                kind load image-archive "${TMP}/chatclient.tar" --name "${CLUSTER_NAME}"
                kind load image-archive "${TMP}/frontend.tar" --name "${CLUSTER_NAME}"
            else
                kind load docker-image "${BACKEND}" "${CHATCLIENT}" "${FRONTEND}" --name "${CLUSTER_NAME}"
            fi
            ;;
        minikube)
            echo "==> Loading into minikube profile '${MINIKUBE_PROFILE}'"
            if [[ "${ENGINE}" == "podman" ]]; then
                for image in "${BACKEND}" "${CHATCLIENT}" "${FRONTEND}"; do
                    podman tag "${image}" "docker.io/library/${image}"
                done
                minikube image load "docker.io/library/${BACKEND}" "docker.io/library/${CHATCLIENT}" \
                    "docker.io/library/${FRONTEND}" -p "${MINIKUBE_PROFILE}"
            else
                minikube image load "${BACKEND}" "${CHATCLIENT}" "${FRONTEND}" -p "${MINIKUBE_PROFILE}"
            fi
            ;;
        *)
            echo "Unknown --load target '${LOAD_INTO}'. Use 'kind' or 'minikube'." >&2
            exit 2
            ;;
    esac
    echo "==> Images are available inside the cluster"
fi

if [[ -n "${RELEASE_FILE}" ]]; then
    cat <<EOF

Deploy this release:

  helm upgrade --install redetim ${CHART_DIR#"${REPO_ROOT}/"} \\
    -n redetim --create-namespace --wait --timeout 10m \\
    -f ${RELEASE_FILE#"${REPO_ROOT}/"} \\
    --description "release ${VERSION}"
EOF
fi
