{{- if .Values.otelCollector.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "redetim.collectorService" . }}
  labels:
    {{- include "redetim.labels" . | nindent 4 }}
    app.kubernetes.io/component: otel-collector
data:
  config.yaml: |
    {{- .Files.Get "files/otel-collector-config.yaml" | nindent 4 }}
{{- end }}
